// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "c9f767bf-8da5-4cf0-978d-b82c0885c4c6";
const char DEVICE_LOGIN_NAME[]  = "3eaece09-00fa-4c75-a35a-7a682f10c604";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onGasAlarmChange();

int analog_gas_out;
bool digital_gas_out;
bool gas_alarm;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(analog_gas_out, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(digital_gas_out, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(gas_alarm, READWRITE, ON_CHANGE, onGasAlarmChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
