// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "52930067-aec3-47af-ba26-532f2389ef95";

const char SSID[]               = "wifi ssid";    // Network SSID (name)
const char PASS[]               = "wIfi Password";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "DEVICE SECRET KEY";    // Secret device password

void onLedChange();

int potentiometer;
int seconds;
bool led;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(potentiometer, READ, ON_CHANGE, NULL, 10);
  ArduinoCloud.addProperty(seconds, READ, 300 * SECONDS, NULL);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
